/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : MindViewFSM.sm
 */




package excitedmind;


public class MindViewFSM
    extends statemap.FSMContext
{
//---------------------------------------------------------------
// Member methods.
//

    public MindViewFSM(MindView owner)
    {
        this (owner, MindViewStateMap.Normal);
    }

    public MindViewFSM(MindView owner, MindViewState initState)
    {
        super (initState);

        _owner = owner;
    }

    @Override
    public void enterStartState()
    {
        getState().entry(this);
        return;
    }

    public void StartEditing()
    {
        _transition = "StartEditing";
        getState().StartEditing(this);
        _transition = "";
        return;
    }

    public void StartInserting()
    {
        _transition = "StartInserting";
        getState().StartInserting(this);
        _transition = "";
        return;
    }

    public void StartMoving()
    {
        _transition = "StartMoving";
        getState().StartMoving(this);
        _transition = "";
        return;
    }

    public void StartRefocusing()
    {
        _transition = "StartRefocusing";
        getState().StartRefocusing(this);
        _transition = "";
        return;
    }

    public void StopEditing(boolean confirm)
    {
        _transition = "StopEditing";
        getState().StopEditing(this, confirm);
        _transition = "";
        return;
    }

    public void StopInserting(boolean confirm)
    {
        _transition = "StopInserting";
        getState().StopInserting(this, confirm);
        _transition = "";
        return;
    }

    public void StopMoving(boolean confirm)
    {
        _transition = "StopMoving";
        getState().StopMoving(this, confirm);
        _transition = "";
        return;
    }

    public void StopRefocusing(boolean confirm)
    {
        _transition = "StopRefocusing";
        getState().StopRefocusing(this, confirm);
        _transition = "";
        return;
    }

    public MindViewState getState()
        throws statemap.StateUndefinedException
    {
        if (_state == null)
        {
            throw(
                new statemap.StateUndefinedException());
        }

        return ((MindViewState) _state);
    }

    protected MindView getOwner()
    {
        return (_owner);
    }

    public void setOwner(MindView owner)
    {
        if (owner == null)
        {
            throw (
                new NullPointerException(
                    "null owner"));
        }
        else
        {
            _owner = owner;
        }

        return;
    }

//---------------------------------------------------------------
// Member data.
//

    transient private MindView _owner;

    //-----------------------------------------------------------
    // Constants.
    //

    private static final long serialVersionUID = 1L;

//---------------------------------------------------------------
// Inner classes.
//

    public static abstract class MindViewState
        extends statemap.State
    {
    //-----------------------------------------------------------
    // Member methods.
    //

        protected MindViewState(String name, int id)
        {
            super (name, id);
        }

        protected void entry(MindViewFSM context) {}
        protected void exit(MindViewFSM context) {}

        protected void StartEditing(MindViewFSM context)
        {
            Default(context);
        }

        protected void StartInserting(MindViewFSM context)
        {
            Default(context);
        }

        protected void StartMoving(MindViewFSM context)
        {
            Default(context);
        }

        protected void StartRefocusing(MindViewFSM context)
        {
            Default(context);
        }

        protected void StopEditing(MindViewFSM context, boolean confirm)
        {
            Default(context);
        }

        protected void StopInserting(MindViewFSM context, boolean confirm)
        {
            Default(context);
        }

        protected void StopMoving(MindViewFSM context, boolean confirm)
        {
            Default(context);
        }

        protected void StopRefocusing(MindViewFSM context, boolean confirm)
        {
            Default(context);
        }

        protected void Default(MindViewFSM context)
        {
            throw (
                new statemap.TransitionUndefinedException(
                    "State: " +
                    context.getState().getName() +
                    ", Transition: " +
                    context.getTransition()));
        }

    //-----------------------------------------------------------
    // Member data.
    //
    }

    /* package */ static abstract class MindViewStateMap
    {
    //-----------------------------------------------------------
    // Member methods.
    //

    //-----------------------------------------------------------
    // Member data.
    //

        //-------------------------------------------------------
        // Constants.
        //

        public static final MindViewStateMap_Normal Normal =
            new MindViewStateMap_Normal("MindViewStateMap.Normal", 0);
        public static final MindViewStateMap_Editing Editing =
            new MindViewStateMap_Editing("MindViewStateMap.Editing", 1);
        public static final MindViewStateMap_Inserting Inserting =
            new MindViewStateMap_Inserting("MindViewStateMap.Inserting", 2);
        public static final MindViewStateMap_Moving Moving =
            new MindViewStateMap_Moving("MindViewStateMap.Moving", 3);
        public static final MindViewStateMap_Refocusing Refocusing =
            new MindViewStateMap_Refocusing("MindViewStateMap.Refocusing", 4);
    }

    protected static class MindViewStateMap_Default
        extends MindViewState
    {
    //-----------------------------------------------------------
    // Member methods.
    //

        protected MindViewStateMap_Default(String name, int id)
        {
            super (name, id);
        }

    //-----------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class MindViewStateMap_Normal
        extends MindViewStateMap_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private MindViewStateMap_Normal(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void StartEditing(MindViewFSM context)
        {

            (context.getState()).exit(context);
            context.setState(MindViewStateMap.Editing);
            (context.getState()).entry(context);
            return;
        }

        @Override
        protected void StartInserting(MindViewFSM context)
        {

            if ( a== 1 && b==0)
            {
                (context.getState()).exit(context);
                // No actions.
                context.setState(MindViewStateMap.Inserting);
                (context.getState()).entry(context);
            }
            else
            {
                super.StartInserting(context);
            }

            return;
        }

        @Override
        protected void StartMoving(MindViewFSM context)
        {

            (context.getState()).exit(context);
            context.setState(MindViewStateMap.Moving);
            (context.getState()).entry(context);
            return;
        }

        @Override
        protected void StartRefocusing(MindViewFSM context)
        {

            (context.getState()).exit(context);
            context.setState(MindViewStateMap.Refocusing);
            (context.getState()).entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class MindViewStateMap_Editing
        extends MindViewStateMap_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private MindViewStateMap_Editing(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void StopEditing(MindViewFSM context, boolean confirm)
        {
            MindView ctxt = context.getOwner();

            (context.getState()).exit(context);
            context.clearState();
            try
            {
                ctxt._owner.stopEditing(confirm);
            }
            finally
            {
                context.setState(MindViewStateMap.Normal);
                (context.getState()).entry(context);
            }

            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class MindViewStateMap_Inserting
        extends MindViewStateMap_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private MindViewStateMap_Inserting(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void StopInserting(MindViewFSM context, boolean confirm)
        {
            MindView ctxt = context.getOwner();

            (context.getState()).exit(context);
            context.clearState();
            try
            {
                ctxt._owner.stopInserting(confirm);
            }
            finally
            {
                context.setState(MindViewStateMap.Normal);
                (context.getState()).entry(context);
            }

            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class MindViewStateMap_Moving
        extends MindViewStateMap_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private MindViewStateMap_Moving(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void StopMoving(MindViewFSM context, boolean confirm)
        {
            MindView ctxt = context.getOwner();

            (context.getState()).exit(context);
            context.clearState();
            try
            {
                ctxt._owner.stopMoving(confirm);
            }
            finally
            {
                context.setState(MindViewStateMap.Normal);
                (context.getState()).entry(context);
            }

            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class MindViewStateMap_Refocusing
        extends MindViewStateMap_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private MindViewStateMap_Refocusing(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void StopRefocusing(MindViewFSM context, boolean confirm)
        {
            MindView ctxt = context.getOwner();

            (context.getState()).exit(context);
            context.clearState();
            try
            {
                ctxt._owner.stopRefocusing(confirm);
            }
            finally
            {
                context.setState(MindViewStateMap.Normal);
                (context.getState()).entry(context);
            }

            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }
}

/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */
